job_name: "EnhancedCodeImprovementAnalysis"
job_description: "Enhanced code analysis with global template variables for contextual adaptation"
job_type: "contextual_code_analysis"

runner_config:
  app_name: "EnhancedCodeImprovementAnalysis"
  session_config:
    user_id: "enhanced_code_analyzer"
    session_id: "enhanced_analysis_session"

agent_config:
  config_path: "config/agent/yaml_examples/enhanced_code_improvement.yaml"
  config_type: "file"

input_config:
  input_files:
    - input_path: "core/gpt_caller.py"
      input_type: "text"
      target_agent: ["SecuritySpecialist", "PerformanceSpecialist"]
    - input_path: "utils/workflow_configuration.py"
      input_type: "text"
      target_agent: ["QualityAssuranceSpecialist", "SecuritySpecialist"]
  
  preview_length: 500

analysis_config:
  template_config_path: "config/template/enhanced_code_improvement.yaml"
  analysis_focus:
    - "Security vulnerabilities and defensive measures"
    - "Performance bottlenecks and optimization opportunities"
    - "Code quality issues and maintainability improvements"
    - "Testing gaps and coverage recommendations"

output_config:
  output_directory: "output"
  output_format:
    - "txt"
    - "json"
  file_naming: "enhanced_analysis_{input_filename}_{timestamp}"
  timestamp_format: "%Y%m%d_%H%M%S"
  include_metadata: true

execution_config:
  track_execution_steps: true
  display_progress: true
  log_level: "INFO"
  error_handling: "continue_on_agent_failure"
  timeout_seconds: 300

report_config:
  include_final_responses: true
  include_code_preview: true
  include_execution_summary: true
  display_results_summary: true