name: MyAwesomeAgent
class: Agent
module: google.adk.agents
model: openai/gpt-4o
instruction: You are an awesome assistant that can search the web and tell the time.
tools:
- get_taipei_time
- google_search
